import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react";
import Faq from "react-faq-component";

const data = {
  rows: [
      {
          title: "How long will it take to reveal my NFT?",
          content: `This may take some time, depending on the complexity of the input photo and the workload of the algorithm (it could take up to 4 hours for each NFT); once it's done, your NFT will automatically reveal.`,
      },
      {
        title: "What will happen to the pictures I uploaded?",
        content: "We only utilize your photos to train our AI model, create your avatars, and then promptly delete both the original photos and the AI model from our servers and the GPU API's servers (where it is processed) within 24 hours. It is important to be aware of other apps that generate profile photos and avatars, as many of them store your data indefinitely and use it for various purposes, including generating fake images featuring your face. Some of these apps may even be affiliated with foreign governments and may potentially access your data.!"
      },
      {
        title: "Can I get a refund?",
        content: "We immediately start training the AI with your photos after uploading your photos and incur high costs for doing that. Therefore we can't offer refunds after that happens. If you need support email us at support@web3me.ai"
      },
      {
        title: "Total Supply? Price? What about Rarity?",
        content: "Our NFT collection is limited to 10,000 one-of-a-kind anime artworks, each of which has been carefully crafted using AI priced at 0.02 eth/each. But we don't stop there. After generating all of these artworks, we'll embark on a massive effort to give each NFT its own traits manually. This extra step helps to ensure that each NFT in our collection is truly special and adds even more value for collectors."
      }
  ],
};


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WEB3ME</title>
        <meta name="description" content="Your Web3 version drawn by an Artificial Intelligence." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="header">
          <a href="/">
            <img className={styles.logo} src="web3me-logo.png"/>
          </a>
          {/* <a href="#" className={styles.buttonGreen}>Connect</a> */}
        </div>
        <main className={styles.main}>
          <div>
            <h3>NFT COLLECTION IN THE ETHEREUM BLOCKCHAIN</h3>
            <h2>web3 version<br/><strong>of yourself</strong><br/>MADE BY AI</h2>
            <p>Convert your profile picture into a stunning anime artwork<br/>generated by our AI and get it as NFT (ERC721A).</p>
            <div className={styles.buttonContainer}>
              <a className={styles.buttonPink} href="https://www.premint.xyz/web3me">PREMINT</a>
            </div>
          </div>
          <div>
            <img className={styles.examples} src="web3me-example.gif" width="600"/>
          </div>
        </main>
        <div className={"latestUploads"}>
          <h2>UNIQUE OUTPUT</h2>
          <p>Each output is unique and generated specifically for the input photo based on the unique characteristics on it.<br/>Objects like leds, hats, toys, face masks can interfere with the way the algorithm processes the photo, resulting in a less accurate or "rare" output.</p>
          <div>
            <ul>
              {
                [1,2,3,4,5].map((item) => (
                  <li><img src={`/generations/${item}.png`}/></li>
                ))
              }
            </ul>
          </div>
        </div>
        <div className={"howSection"}>
          <h2>HOW IT WORKS</h2>
          <div className={"howList"}>
            <div>
              <h3>Mint your NFT</h3>
              <p>In order to use WEB3ME and mint your NFT, you will need to have a MetaMask wallet set up and connected to your web browser; then you go to the mint page, click on the 'mint now' button and wait until the transaction gets succeed status.</p>
            </div>
            <div>
              <h3>Submit your photo</h3>
              <p>After you got succeed status on the previous step you will be redirected to a page with our legal terms and the upload profile picture area, which you will need to provide your desired photo so the AI can work on it.</p>
            </div>
            <div>
              <h3>Wait the reveal</h3>
              <p>Once you submitted your photo, the algorithm will begin processing it to generate the output. This may take some time, depending on the complexity of the input photo and the workload of the algorithm; once it's done, your NFT will automatically reveal.</p>
            </div>
          </div>
        </div>
        <div className={"faqSection"}>
          <h2>FAQ</h2>
          <div className={"faqList"}>
          <Faq
                data={data}
            />
          </div>
        </div>
        <footer>
          <a href="#">Verified Smart Contract 0x123213123213213123</a>
        </footer>
      </>
    </div>
  )
}
